package dao;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.Hibernate;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

import util.HibernateUtil;
import model.Movie;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the movie table.
 * Any customizations belong here.
 */
public class MovieDAO {
	
	
	public Movie getById(int id) {
		Session session = HibernateUtil.getSessionFactory().openSession();
		Transaction transaction = null;
		Movie movie = null;
		try {
			transaction = session.beginTransaction();
			movie = (Movie) session.get(Movie.class, id);
			Hibernate.initialize(movie.getGenres());
			transaction.commit();
		}catch(HibernateException he) {
			he.printStackTrace();
		}finally {
			if(session != null) {
				try { 
					session.close(); 
				} catch(HibernateException he){
					he.printStackTrace();
					}
			}
		}
		return movie;
	}
	
	@SuppressWarnings("unchecked")
	public List<Movie> getAll() {
		Session session = HibernateUtil.getSessionFactory().openSession();
		Transaction transaction = null;
		List<Movie> movies = null;
		try {
			transaction = session.beginTransaction();
			Query query = session.createQuery("from Movie");
			movies = query.list();
			for(Movie movie : movies)
				Hibernate.initialize(movie.getGenres());
			
			transaction.commit();
		}catch(HibernateException he) {
			he.printStackTrace();
		}finally {
			if(session != null) {
				try { 
					session.close(); 
				} catch(HibernateException he){
					he.printStackTrace();
					}
			}
		}
		return movies;
	}
	
	@SuppressWarnings("unchecked")
	public List<Movie> findByName(String movieName){
		Session session = HibernateUtil.getSessionFactory().openSession();
		Transaction transaction = null;
		List<Movie> movies = null;
		try {
			transaction = session.beginTransaction();
			
			Criteria criteria = session.createCriteria(Movie.class);
			criteria.add(Restrictions.like("name", "%"+movieName+"%"));
			
			movies = criteria.list();
			
			for(Movie movie : movies)
				Hibernate.initialize(movie.getGenres());
			
			transaction.commit();
			
		}catch(HibernateException he) {
			he.printStackTrace();
		}finally {
			if(session != null) {
				try { 
					session.close(); 
				} catch(HibernateException he){
					he.printStackTrace();
					}
			}
		}
		return movies;
		
	}
}